#!/bin/bash

brightness=$(xbacklight | cut -d . -f 1)
echo $brightness%

case $BLOCK_BUTTON in
    3) xbacklight -set $((100 - $brightness)) ;;  # right click, invert brightness level
    4) xbacklight -inc 5 ;;  # scroll up
    5) xbacklight -dec 5 ;;  # scroll down
esac
