# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "v4l2loopback" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback.out ];
  boot.extraModprobeConfig = ''options v4l2loopback exclusive_caps=1 video_nr=9 card_label="obs"'';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f28ed3c5-31e4-4342-84fd-4c55f3df36a9";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-2483af01-e0ec-4546-b2d4-ba8610366ba8".device = "/dev/disk/by-uuid/2483af01-e0ec-4546-b2d4-ba8610366ba8";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2F02-DB36";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e6a83682-9b52-46a4-a4c3-d1007b9c69bd"; }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nix.settings.max-jobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
