# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "coretemp" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fc070df3-4fcb-4a78-abd8-f1c6930289d1";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-aa544102-f6e0-40d6-85b9-e9f2a8d67921".device = "/dev/disk/by-uuid/aa544102-f6e0-40d6-85b9-e9f2a8d67921";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C9F5-5215";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/fd21b85b-f265-47cc-a01d-eba04afa88f6"; }
  ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
